name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or any branch you want to trigger the action for

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Update to Java 21
          distribution: 'temurin'  # Correct distribution

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Generate version using year.month.day format
      - name: Generate version
        run: |
          VERSION=$(date +'%Y.%m.%d')  # Format: year.month.day
          echo "Generated version: ${VERSION}"
          if [ -z "$VERSION" ]; then
            echo "Error: VERSION is empty"
            exit 1
          fi

      # Step 5: Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          DOCKER_IMAGE_NAME=speedwing/ft-aquarium-node
          DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${VERSION}"
          DOCKER_IMAGE_LATEST="${DOCKER_IMAGE_NAME}:latest"
          echo "Building Docker image with tag: ${DOCKER_IMAGE}"
          docker build -t "${DOCKER_IMAGE}" -t "${DOCKER_IMAGE_LATEST}" --push .
        
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
